#!/bin/bash
echo "This is the first line of code"
echo "This is the second line of code"
echo "This is the third line of code"
echo "This is the fourth line of code"
echo "This is the fifth line of code"
echo "This is the sixth line of code"
echo "This is the seventh line of code"
echo "This is the eightth line of code"
echo "This is the nineth line of code"
